Wf60 to Wf62 spec edit recommendations
GovStackWorkingGroup/bb-workflow pull request #74
Opened 2023-06-28 00:48 UTC by FaraiMutero

Wf60 to Wf62 spec edit recommendations

2023-06-28 14:10 UTC, taylordowns2000 requested changes
maybe a few typos, please see change requests, but otherwise I'm happy. request a review from @aarelaponin please

2023-06-28 14:10 UTC, taylordowns2000 commented on api/swagger.yaml
> +      operationId: start
start or stop?

2023-06-28 14:10 UTC, taylordowns2000 commented on api/swagger.yaml
> +        Create a process instance and register it with the execution engine
wrong maybe?

2023-06-28 14:10 UTC, taylordowns2000 commented on api/swagger.yaml
> +          description: Invalid processId. Process does not exist
This would be a not found, not an "invalid"

2023-07-12 14:21 UTC, taylordowns2000 commented on api/swagger.yaml
> +      operationId: start
fixed in [caf5c3e](https://github.com/GovStackWorkingGroup/bb-workflow/pull/74/commits/caf5c3ed7a1fb69f4f816ae25ef928378f7294e9)

2023-07-12 15:52 UTC, FaraiMutero commented on api/swagger.yaml
> +        Create a process instance and register it with the execution engine
Resolved. Thanks

2023-08-17 13:15 UTC, taylordowns2000 approved these changes

2023-08-17 13:15 UTC, taylordowns2000 approved these changes

2023-08-23 14:30 UTC, FaraiMutero commented
Conflicts resolved. @taylordowns2000 please check if changes are pulling through on your end?

2023-08-23 14:30 UTC, closed without merging